### ISSUE TITLE
Uitleg uitbreiden over het gebruik van de template

### ISSUE THREAD

**Issue by folkertdeheus** [hanaim-webtech/WT_IS_Bp#41]
Onderstaande uitleg heb ik gebruikt om klasgenoten wegwijs te maken in het gebruik van de template:

"
In de template hebben ze een MVC structuur, ofwel Model-View-Controller na proberen te bootsen. Hoewel dat steeds populairder is, is dat niet standaard voor php zo. Dat maakt het nu een beetje omslachtig, maar als eenmaal het kwartje valt (dat zal deze course denk ik niet gebeuren) is het wel een prettige manier van data scheiden.

Die structuur zorgt ervoor dat de data afhandeling en de dataweergave van elkaar gescheiden wordt. Model staat voor de werkende kant van de website, de View is wat de gebruiker ziet, en de Controller is waarmee de user acties uitvoert. Meer dan dat hoef je nu niet te weten om die template een beetje te begrijpen.

*Hoe werkt dat dan precies in de template?* In de map `webserver` -> `applicatie` staan een paar mappen die van belang zijn. Daar staat ook een readme in over de structuur. De map `applicatie` moet je zien als de hoofdmap van je website.

De eerste, en voor jullie belangrijkste map is `public`. Daarin gaat ALLE statische informatie van de website. Daaronder vallen alle `.css` documenten, alle afbeeldingen, alle lettertypes, filmpjes, audio, etc. Die map krijgt waarschijnlijk de volgende structuur (ongeveer):
```
applicatie
-> public
   -> css
      style.css
   -> fonts
      font1.ttf
   -> images
      afbeelding1.jpg
      afbeelding2.png
   router.php
```
Op die `router.php` kom ik zo nog even terug, die is ook belangrijk, die moet je namelijk aanpassen

De volgende map die belangrijk is, is `src` -> `views`. Hierin gaan alle documenten die op de achtergrond handelingen uitvoeren. Hier ga je vooral de php scripts in stoppen. Nu staat daar al een `index.php` in, die zorgt ervoor dat wanneer je nu naar `localhost` "surft", je de php informatie te zien krijgt. `index.php` is de startpagina van je website, alle "magic" gebeurt vanaf hier en is dan ook je homepage. In php files kan je ook gewoon html tags zetten, dus als je nu de `index.html` kopieert en plakt naar de .php, dan zou je (als het goed is) jouw website moeten zien.

Dan die `router.php` nog. Die ziet er ingewikkeld uit, maar gelukkig is 75% commentaar, en 75% van wat geen commentaar is kun je negeren. Er zijn hier maar 2 regels van belang:
**Op regel 17** staat `if ($urlPad === '' || $urlPad === '/') {`. Dit betekend dat wanneer er niets achter "localhost" in de adresbalk staat, je naar `require_once 'src/views/index.php';` die pagina verwezen wordt, wat je homepage is. Nu ga je links (`<a>` elementen) gebruiken om je gebruikers naar verschillende pagina's te laten gaan. Dat doe je door bijvoorbeeld de volgende link te maken:
```html
<a href="/maakAccount">Maak account</a>
```
Nu stuur je de gebruiker door naar `localhost/maakAccount`. In de router moet je nu vertellen dat die link bestaat, en naar welk bestand die dan naartoe gestuurd moet worden. In `router.php` voeg je dan de volgende regel toe:
```php
17 if ($urlPad === '' || $urlPad === '/') {
18 require_once 'src/views/index.php';
19 } elseif ($urlPads === '/maakAccount') {
20 require_once 'src/views/maakAccount.php';
21 } else {
22 // de rest
```
Voor elke link die je maakt, maak je dus een nieuwe pagina en voeg je die in de router toe

De 2e regel die van belang is, is regel **29**:
```php
29  '/\.(?:css|png|jpg|jpeg|svg|woff|woff2|ttf|otf|html)$/',
```
Deze regel bekijkt naar bekende bestandstypen, en bepaald of ze gelanden mogen worden. Hier staan geen filmformaten (of audioformaten voor @Micha#4352 ). Die moeten hier aan toegevoegd worden:
```php
29  '/\.(?:css|png|jpg|jpeg|svg|woff|woff2|ttf|otf|html|mov|mp4|webm|mp3)$/',
```
"

**Comment by sanmai-NL** [comment]
Dank je, @folkertdeheus. Dat de README nietszeggend is, daar ben ik het natuurlijk niet mee eens. 😉 Daar staat hetzelfde in als wat jij hier toelicht, behalve het benoemen dat HTTP-requests op `router.php` binnenkomen. Standaard zou je dat laatste en het verhaal omheen in de les gedemonstreerd zien, maar ik zal jouw schriftelijke uitleg ook opnemen.

**Comment by folkertdeheus** [comment]
Ik had hem even moeten doorlezen voor ik hem hier ging plaatsen, heb dat er uitgehaald. Nietszeggend is het inderdaad niet, maar het behoeft denk ik wel iets meer uitleg. Wat ik verder heb gedaan is inderdaad een uitgebreidere uitleg geven dan in het commentaar van de router.php ook al staat benoemd. Ik ben het er ook mee eens dat een uitleg tijdens de les het beste zou zijn, zeker omdat het nogal ingewikkeld kan zijn voor mensen met weinig ervaring.

**Comment by sanmai-NL** [comment]
Ik heb jouw toevoegingen vertaald naar een uitbreiding van de README.
